server:
  port: 44144
spring:
  application:
    name: gateway-api
  mvc:
    static-path-pattern: /content/**
  web:
    resources:
      static-locations:
        - file:///D:/covers
        - file:///D:/songs