server:
  port: 8888
spring:
  application:
    name: user-service
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      port: 27017
      database: spotify-dev
      auto-index-creation: true
      host: localhost
logging:
  level:
    ru.shanalotte: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/