eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: music-scanner
  main:
    web-application-type: none
