spring:
  application:
    name: music-service
  data:
    mongodb:
      port: 27017
      database: spotify
      auto-index-creation: true
      host: localhost
logging:
  level:
    ru.shanalotte: debug
server:
  port: 12345
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/